image: docker:latest

stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_IMAGE: ebispot/gwas-deposition-template

# always build an image tagged with the commit SHA from master
build:
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
   - docker pull $CI_REGISTRY_IMAGE:latest
   - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
   - master

# if a tag is created create an images with the tag and a latest
build_release:
  variables:
    GIT_STRATEGY: none
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
   - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
   - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
   - docker push $CI_REGISTRY_IMAGE:latest
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
   - tags

deploy_staging:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - mkdir -p /root/.kube
    - echo ${SANBOX_KUBECONF} | base64 -d > /root/.kube/conf
    - helm init
    - helm upgrade --install --set k8Namespace=default,image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA gwas-template-service ./k8chart/ --wait
  environment:
    name: sandbox
    url: http://192.30.252.153/template
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: http://www.ebi.ac.uk/gwas/submissions/template
  when: manual
  only:
   - tags
