image: docker:latest
 
stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
   - docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}"
   
build:
  stage: build
  script:
   - docker build -t ebispot/gwas-deposition-template:1.$CI_PROJECT_BUILDS .
   - docker tag ebispot/gwas-deposition-template:1.$CI_PROJECT_BUILDS ebispot/gwas-deposition-template:latest
   - docker push ebispot/gwas-deposition-template:1.$CI_PROJECT_BUILDS ebispot/gwas-deposition-template:latest
   - docker logout
