language: python
python:
  - "3.6"
branches:
  only:
  - master
  - Add_testing
before_install:
  - mkdir logs
install:
  - python setup.py -q install
  - pip install -r requirements.txt
script:
  - pytest --cov-report html --cov sumstats_service --verbose
  - coverage xml
  - python-codacy-coverage -r coverage.xml
