language: python
python:
  - "3.6"
branches:
  only:
  - master
  - dev
addons:
  sonarcloud:
    organization: "gwas-ebi"
before_install:
  - mkdir logs
install:
  - python setup.py -q install
  - pip install -r requirements.txt
script:
  - coverage run -m pytest
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - sonar-scanner -Dsonar.organization=gwas-ebi -Dsonar.projectKey=gwas-template-services -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6 -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.exclusions=tests/*,build/**